Ext.define('CRM.model.customerManagement.intentOrder.IntentOrder', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'id',
        type: 'int'
    }, {
        name: 'orderID',
        type: 'string'
    }, {
        name: 'eventName',
        type: 'string'
    }, {
        name: 'customerName',
        type: 'string'
    }, {
        name: 'customerID',
        type: 'string'
    }, {
        name: 'orderState',
        type: 'string'
    }, {
        name: 'contactID',
        type: 'string'
    }, {
        name: 'ourRepresentative',
        type: 'string'
    }, {
        name: 'deliveryDate',
        type: 'string'
    }, {
        name: 'operateType',
        type: 'string'
    }, {
        name: 'transactionPrice',
        type: 'string'
    }, {
        name: 'remark',
        type: 'string'
    }, {
        name: 'duration',
        type: 'string'
    }, {
        name: 'isAbolished',
        type: 'string'
    }, {
        name: 'orderTypeName',
        type: 'string'
    }, {
        name: 'orderStateName',
        type: 'string'
    }, {
        name: 'deliveryTypeName',
        type: 'string'
    }, {
        name: 'operateTypeName',
        type: 'string'
    }, {
        name: 'contactName',
        type: 'string'
    }, {
        name: 'opportunityID',
        type: 'string'
    }, {
        name: 'ourTelephone',
        type: 'string'
    }, {
        name: 'phoneNumber',
        type: 'string'
    }, {
        name: 'customerContact',
        type: 'string'
    }, {
        name: 'customerContactName',
        type: 'string'
    }, {
        name: 'requirement',
        type: 'string'
    }, {
        name: 'valueanalys',
        type: 'string'
    }, {
        name: 'policymakers',
        type: 'string'
    }, {
        name: 'cognitiveanalys',
        type: 'string'
    }, {
        name: 'eventID',
        type: 'int'
    }, {
        name: 'status',
        type: 'string'
    } ]
});