Ext.define('CRM.model.systemManagement.groupManagement.GroupInfo', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'userID',
        type: 'int'
    }, {
        name: 'groupID',
        type: 'int'
    }, {
        name: 'jobID',
        type: 'string'
    }, {
        name: 'password',
        type: 'string'
    }, {
        name: 'userName',
        type: 'string'
    }, {
        name: 'realName',
        type: 'string'
    }, {
        name: 'company',
        type: 'string'
    }, {
        name: 'departmentID',
        type: 'int'
    }, {
        name: 'projectTeamID',
        type: 'int'
    }, {
        name: 'job',
        type: 'string'
    }, {
        name: 'jobTitle',
        type: 'string'
    }, {
        name: 'email',
        type: 'string'
    }, {
        name: 'mobile',
        type: 'string'
    }, {
        name: 'officePhone',
        type: 'string'
    }, {
        name: 'education',
        type: 'string'
    }, {
        name: 'entryTime',
        type: 'string'
    }, {
        name: 'descriptions',
        type: 'string'
    } ]
});