Ext.define('CRM.store.systemManagement.authorizationManagement.AuthorizationOperationMenu', {
    extend: 'Ext.data.TreeStore',
    root: {
        text: 'root',
        id: 'operation_0',
        expanded: false,
        children: [ {
            text: '客户基本信息',
            id: 'operation_00',
            checked: false,
            leaf: false,
            children: [ {
                text: '简单检索',
                checked: false,
                leaf: true
            }, {
                text: '高级检索',
                checked: false,
                leaf: true
            }, {
                text: '查看联系人',
                checked: false,
                leaf: true
            }, {
                text: '查看合作履历',
                checked: false,
                leaf: true
            }, {
                text: '添加客户',
                checked: false,
                leaf: true
            }, {
                text: '编辑客户',
                checked: false,
                leaf: true
            }, {
                text: '删除客户',
                checked: false,
                leaf: true
            } ]
        }, {
            text: '客户来源',
            id: 'operation_01',
            checked: false,
            leaf: false,
            children: [ {
                text: '简单检索',
                checked: false,
                leaf: true
            }, {
                text: '高级检索',
                checked: false,
                leaf: true
            }, {
                text: '添加客户来源',
                checked: false,
                leaf: true
            }, {
                text: '编辑客户来源',
                checked: false,
                leaf: true
            }, {
                text: '删除客户来源',
                checked: false,
                leaf: true
            } ]
        }, {
            text: '客户联系',
            id: 'operation_02',
            checked: false,
            leaf: false,
            children: [ {
                text: '简单检索',
                checked: false,
                leaf: true
            }, {
                text: '高级检索',
                checked: false,
                leaf: true
            }, {
                text: '查看客户反馈',
                checked: false,
                leaf: true
            }, {
                text: '添加客户联系',
                checked: false,
                leaf: true
            }, {
                text: '编辑客户联系',
                checked: false,
                leaf: true
            }, {
                text: '删除客户联系',
                checked: false,
                leaf: true
            } ]
        } ]
    }
});