Ext.define('CRM.model.salesManagement.salesEvent.SalesEventListModel', {
    extend: 'Ext.data.Model',
    fields: [ {
        // id
        name: 'eventID',
        type: 'int'
    }, {
        // 销售机会概要
        name: 'eventName',
        type: 'string'
    }, {
        name: 'customerID',
        type: 'string'
    }, {
        // 客户
        name: 'customerName',
        type: 'string'
    }, {
        name: 'contactID',
        type: 'string'
    }, {
        // 客户联系人
        name: 'contactName',
        type: 'string'
    }, {
        // 机会日期
        name: 'submitDate',
        type: 'string'
    }, {
        // 备注
        name: 'remarks',
        type: 'string'
    }, {
        // 提交人员
        name: 'submitPersonName',
        type: 'string'
    }, {
        name: 'status',
        type: 'string'
    }, {
        // 机会状态
        name: 'statusName',
        type: 'string'
    }, {
        name: 'isAbolished'
    }, {
        name: 'sort',
        type: 'int'
    } ]
});