Ext.define('CRM.model.customerManagement.cooperator.Cooperator', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'cooperatorID',
        type: 'int'
    }, {
        name: 'cooperatorName',
        type: 'string'
    }, {
        name: 'cooperatorCity',
        type: 'string'
    }, {
        name: 'cooperatorIndustry',
        type: 'string'
    }, {
        name: 'cooperatorScale',
        type: 'int'
    }, {
        name: 'cooperationDate',
        type: 'string'
    }, {
        name: 'projectNumber',
        type: 'int'
    }, {
        name: 'copAnaNumber',
        type: 'int'
    }, {
        name: 'cooperatorType',
        type: 'string'
    }, {
        name: 'cooperatorTelephone',
        type: 'string'
    }, {
        name: 'cooperatorEmail',
        type: 'string'
    }, {
        name: 'cooperatorFax',
        type: 'string'
    }, {
        name: 'cooperatorWebsite',
        type: 'string'
    }, {
        name: 'cooperatorAddress',
        type: 'string'
    }, {
        name: 'cooperatorRemark',
        type: 'string'
    }, {
        name: 'cooperatorDetail',
        type: 'string'
    }, {
        name: 'industryDisplay',
        type: 'string'
    }, {
        name: 'scaleDisplay',
        type: 'string'
    }, {
        name: 'typeDisplay',
        type: 'string'
    } ]
});
