Ext.define('CRM.model.customerManagement.cooperator.CooperatorAnalysisModel', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'copAnalysisID',
        type: 'int'
    }, {
        name: 'cooperatorID',
        type: 'string'
    }, {
        name: 'cooperatorName',
        type: 'String'
    }, {
        name: 'advantageField',
        type: 'string'
    }, {
        name: 'disadvantageField',
        type: 'string'
    }, {
        name: 'managementAbility',
        type: 'string'
    }, {
        name: 'managementAbilityName',
        type: 'string'
    }, {
        name: 'responseSpeed',
        type: 'string'
    }, {
        name: 'responseSpeedName',
        type: 'string'
    }, {
        name: 'trustDegree',
        type: 'string'
    }, {
        name: 'trustDegreeName',
        type: 'string'
    }, {
        name: 'engLevelEvaluation',
        type: 'string'
    }, {
        name: 'cooperationSummarize',
        type: 'string'
    }, {
        name: 'comphsAnalysis',
        type: 'string'
    }, {
        name: 'descriptions',
        type: 'string'
    }, {
        name: 'createTime',
        type: 'string'
    } ]
});