Ext.define('CRM.model.customerManagement.cooperator.ProjectItem', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'cooperatorID',
        type: 'int'
    }, {
        name: 'cooperationProjectID',
        type: 'int'
    }, {
        name: 'cooperatorName',
        type: 'string'
    }, {
        name: 'expectedBeginTime',
        type: 'string'
    }, {
        name: 'expectedEndTime',
        type: 'string'
    }, {
        name: 'realBeginTime',
        type: 'string'
    }, {
        name: 'realEndTime',
        type: 'string'
    }, {
        name: 'projectName',
        type: 'string'
    }, {
        name: 'projectScale',
        type: 'string'
    }, {
        name: 'cooperatorScale',
        type: 'string'
    }, {
        name: 'cooperatorPeopleNumber',
        type: 'string'
    }, {
        name: 'principalWe',
        type: 'string'
    }, {
        name: 'principalCooperator',
        type: 'string'
    }, {
        name: 'principalCooperatorPhone',
        type: 'string'
    }, {
        name: 'projectType',
        type: 'string'
    }, {
        name: 'projectTypeDisplay',
        type: 'string'
    }, {
        name: 'projectDetail',
        type: 'string'
    }, {
        name: 'appraisal',
        type: 'string'
    }, {
        name: 'projectTypeDisplay',
        type: 'string'
    } ]
});
