Ext.define('CRM.model.activityManagement.activity.Activity', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'activityID',
        type: 'int'
    }, {
        name: 'activityType',
        type: 'string'
    }, {
        name: 'activityTypeName',
        type: 'string'
    }, {
        name: 'activityAim',
        type: 'string'
    }, {
        name: 'activityName',
        type: 'string'
    }, {
        name: 'activityStartTime',
        type: 'string'
    }, {
        name: 'activityEndTime',
        type: 'string'
    }, {
        name: 'activityRange',
        type: 'string'
    }, {
        name: 'activityRangeName',
        type: 'string'
    }, {
        name: 'activityPlace',
        type: 'string'
    }, {
        name: 'activityLeader',
        type: 'string'
    }, {
        name: 'activityModifer',
        type: 'string'
    }, {
        name: 'activityOurPersonNO',
        type: 'int'
    }, {
        name: 'activityFunds',
        type: 'string'
    }, {
        name: 'activityPeriod',
        type: 'string'
    }, {
        name: 'activityPeriodName',
        type: 'string'
    }, {
        name: 'activityMember',
        type: 'string'
    }, {
        name: 'memberName',
        type: 'string'
    }, {
        name: 'customerName',
        convert: function(v, record) {
            return record.get('activityMember').split(',');
        }
    }, {
        name: 'activityDetail',
        type: 'string'
    }, {
        name: 'activityState',
        type: 'string'
    }, {
        name: 'activityStateName',
        type: 'string'
    }, {
        name: 'activityComment',
        type: 'string'
    }, {
        name: 'activityPlan',
        type: 'string'
    }, {
        name: 'activityEmphasis',
        type: 'string'
    }, {
        name: 'activityEmphasisName',
        type: 'string'
    }, {
        name: 'activityMeans',
        type: 'string'
    } ]
});