Ext.define('CRM.model.customerManagement.customerProfiles.CoopResume', {
    extend: 'Ext.data.Model',
    fields: [ {
        name: 'coopResumeID',
        type: 'int'
    }, {
        name: 'customerID',
        type: 'string'
    }, {
        name: 'projectName',
        type: 'string'
    }, {
        name: 'expBeginDate',
        type: 'string'
    }, {
        name: 'expEndDate',
        type: 'string'
    }, {
        name: 'beginDate',
        type: 'string'
    }, {
        name: 'endDate',
        type: 'string'
    }, {
        name: 'projectScale',
        type: 'string'
    }, {
        name: 'peopleNumber',
        type: 'string'
    }, {
        name: 'principalThey',
        type: 'string'
    }, {
        name: 'principalWe',
        type: 'string'
    }, {
        name: 'projectDetail',
        type: 'string'
    }, {
        name: 'projectType',
        type: 'string'
    }, {
        name: 'appraisal',
        type: 'string'
    }, {
        name: 'isAbolished',
        type: 'string'
    }, {
        name: 'descriptions',
        type: 'string'
    }, {
        name: 'projectTypeName',
        type: 'string'
    } ]
});